name: Build and Deploy Windows App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Wine
        run: | 
          sudo apt-get update
          sudo apt-get install wine
          sudo apt-get install libwine
          sudo apt install osslsigncode

      - name: Install Wine32 with Multiarch
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install wine32

      - name: Install dependencies
        run: npm install

      - name: Install Electron Builder
        run: npm install -g electron-builder

      - name: Build Electron App for Windows
        run: electron-builder build --windows --publish never

      - name: Creating Files
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "cert.pem"
          FILE_DATA: ${{ secrets.CODESIGN_CERT }}
          
      - name: Creating Files
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "key.pem"
          FILE_DATA: ${{ secrets.CODESIGN_KEY }}

      - name: Sign EXE
        run: |
          osslsigncode sign -certs cert.pem -key key.pem -in "dist/20-20-20-refresh Setup 1.0.0.exe" -out "dist/signed-20-20-20-refresh Setup 1.0.0.exe"

      - name: Upload
        uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.DO_ACCESS_KEY_ID}}
          secret_key: ${{ secrets.DO_SECRET_ACCESS_KEY }}
          space_name: 20-20-20
          space_region: blr1
          source: dist/20-20-20-refresh Setup 1.0.0.exe
          out_dir: application

