name: Build Windows App

on:
  push:
    branches:
      - main  # Adjust the branch as per your requirements

jobs:
  build:
    runs-on: windows-latest  # Specify the operating system for the build
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20  # Adjust the Node.js version as per your requirements

    - name: Install dependencies
      run: npm install  # Make sure this installs all required dependencies

    - name: Install Electron Builder
      run: npm install -g electron-builder

    - name: Build Electron App for Windows
      run: npm run electron-builder build --windows

    - name: Archive dist folder
      uses: actions/upload-artifact@v2
      with:
        name: dist-windows  # Name of the artifact
        path: dist          # Path to the folder you want to archive and store as an artifact
