name: Build and Deploy Windows App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Electron Builder
        run: npm install -g electron-builder

      - name: Build Electron App for Windows
        run: electron-builder build --windows --publish never

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-executable
          path: dist/20-20-20-refresh Setup 1.0.0.exe
            
      - name: Upload to DigitalOcean Spaces
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: 20-20-20
          AWS_ACCESS_KEY_ID: ${{ secrets.DO_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SECRET_ACCESS_KEY }}
          AWS_REGION: BLR1
          SOURCE_DIR: dist/20-20-20-refresh\ Setup\ 1.0.0.exe


