name: Update Release Assets

on:
  push:
    branches:
      - main

jobs:
  update_release_assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Install Electron Builder
        run: npm install -g electron-builder

      - name: Build Electron App for Windows
        run: electron-builder build --windows --publish never

      - name: List Release Assets
        id: list_assets
        run: |
          ASSETS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases/tags/v1.0.0/assets)
          echo "::set-output name=assets::$ASSETS"

      - name: Determine If Asset Exists
        id: asset_exists
        run: |
          if echo "${{ steps.list_assets.outputs.assets }}" | grep -q "20-20-20-refresh Setup 1.0.0.exe"; then
            echo "Asset exists."
            echo "::set-output name=asset_exists::true"
          else
            echo "Asset does not exist."
            echo "::set-output name=asset_exists::false"
          fi

      - name: Delete Existing Asset
        if: steps.asset_exists.outputs.asset_exists == 'true'
        run: |
          ASSET_ID=$(echo "${{ steps.list_assets.outputs.assets }}" | jq -r '.[] | select(.name == "20-20-20-refresh Setup 1.0.0.exe").id')
          curl -X DELETE -H "Authorization: token ${{ secrets.GH_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/assets/${ASSET_ID}"

      - name: Upload New Asset
        if: steps.asset_exists.outputs.asset_exists == 'false'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.list_assets.outputs.release_id }}/assets?name=20-20-20-refresh Setup 1.0.0.exe
          asset_path: dist/20-20-20-refresh Setup 1.0.0.exe
          asset_name: 20-20-20-refresh Setup 1.0.0.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
